spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:43306/areaManagementFunction
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8888

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
