version: "3.9"

services:
  # 使用 Dockerfile 构建容器
  #  centos1:
  #    build:
  #      context: ./redis
  #      dockerfile: Dockerfile
  mysql1:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql1
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1235

  #  mysql1:
  #    image: mysql
  #    ports:
  #      - "43306:3306"
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=root1235
  redis1:
    image: redis
    ports:
      - "46379:6379"
  minio1:
    image: quay.io/minio/minio
    ports:
      - "49000:9000"
      - "49090:9090"
    env_file:
      - minio/config.env
    volumes:
      - minio1:/root/data
    command: server --console-address ":9090"
    privileged: true
  nacos1:
    image: nacos/nacos-server:v2.2.1
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos1/conf:/home/nacos/conf
      - ./nacos1/logs:/home/nacos/logs
    env_file:
      - nacos1/config.env
    links:
      - mysql1


volumes:
  minio1:

