services:
  # 使用 Dockerfile 构建容器
  #  centos1:
  #    build:
  #      context: ./redis
  #      dockerfile: Dockerfile
  mysql1:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql1
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1235
  #  mysql2:
  #    image: mysql2
  #    ports:
  #      - "43303:3306"
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=root1235
  #    depends_on:
  #      - mysql1
  #    command:
  mysql-db:
    # 指定容器的名称
    container_name: mysql
    # 指定镜像和版本
    image: mysql
    ports:
      - "43306:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '2g'
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/config:/etc/mysql/conf.d"


  #  sentinel1:
  #    image: bitnami/redis-sentinel
  #    privileged: true
  #    ports:
  #      - "8858:8858"
  #      - "26379:6379"
  #    container_name: sentinel1
  #    environment:
  #      - REDIS_MASTER_HOST=redis1
  #    depends_on:
  #      - redis1

  seata-server45:
    image: "seataio/seata-server:1.6.1"


  seata-server-1:
    image: seataio/seata-server:${seata-version}
    container_name: seata-server-1
    ports:
      - "17091:7091"
      - "18091:8091"
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
      - SEATA_IP=seata_ip
      - SEATA_PORT=8091
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"        #设置系统时区
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"  #设置时区
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
      - "./seata-server/resources:/seata-server/resources"

  seata-server-2:
    image: seataio/seata-server:${latest-release-version}
    container_name: seata-server-2
    ports:
      - "27092:7091"
      - "28092:8091"
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
      - SEATA_IP=seata_ip
      - SEATA_PORT=8092
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"        #设置系统时区
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"  #设置时区
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
      - "./seata-server/resources:/seata-server/resources"

volumes:
  minio1:
