[tool.poetry]
name = "store-python"
version = "0.1.0"
description = ""
authors = ["BlackBox <vwvmnu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.2"
pandas = "^2.2.3"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
