spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    dynamic:
      # 设置默认的数据源
      primary: master
      # 严格匹配,false使用默认数据源,true未匹配报出异常
      strict: false
      druid:
        #初始化建立1个连接
        initial-size: 1
        #最大建立20个连接
        max-active: 20
        #最小空闲连接1
        min-idle: 1
        #获取连接的最大时间
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:43306/usercenter
          username: root
          password: root
        docker1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:43306/usercenter
          username: root
          password: root

  # email 配置
  mail:
    host: smtp.qq.com
    username: 1647010108@qq.com
    password: xvntllobycoiejba
    default-encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
    #启用识图解析
    enabled: true
    # 禁用缓存
    cache: false
    # 视图路径
    prefix:
      classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  #rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 45672
    username: admin
    password: admin
    virtual-host: /
  #redis配置
  redis:
    host: localhost
    port: 46379
    password: root




mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml, classpath:mappers/adminMapper/*Mapper.xml
  #配置类型别名对应的包
  type-aliases-package: org.vwvm.store.beans.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #全局主键自增
      id-type: auto
server:
  port: 9090
  servlet:
    context-path: /

